spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:4540/demo
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    debug: true
    host: smtp.xxx.com
    port: 587
    username: xxx@xxxx.com
    password: xxxxxxxx
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true